### ISSUE TITLE
TODO before release

### ISSUE THREAD

**Issue by lambduli** [lambdulus/frontend#1]
- [ ] ~~First Box into the URL~~
  - [ ] ~~SLI + Exercise + Strategy + SDE + User-Defined-Macros~~
- [x] Minimize/Maximize Icon/Button in Box Title Bar
- [x] Tabs / Notebooks
- [x] Box local Settings
- [x] Macros for Untyped Lambda - make Notebook scope or not?
  - [ ] ~~Macro Box should have Pencil in the Custom part of the Box Top Bar - when clicked - Macro Box will be editable again and allows to change the definition of the Macro - maybe it should only allow to change the definition - not the name~~
- [ ] Serialization - Export
  - [ ] Breakpoint serialization -- (When Breakpoint attached - replace the current AST Node with almost perfect clone - change the Symbol value to Symbol.for(Date.now().toString()) or something -- ~~this should be unique enough~~ -- better yet - use some unique-key-generator, store the seed/state of it to the exported notebook and then have it the correct way
        Also - remember calling JSON.stringify(someSymbol) will result in undefined, you should use Symbol.keyFor or someSymbol.toString() -- this means some specific transformation/serialization is needed before stringifying 
- [x] Deserialization - Import
  - [x] AST decoding
- [x] Clear Button - clears the whole Notebook content
- [x] Dark Mode
- [x] Better Cleaner UI
  - [x] Less heavy on area
  - [x] More text-file like (?)
- [x] Monaco Editor Integration
  - [x] Syntax Highlighting
  - [x] Parenthesis Pairing
- [x] Graphical Controlling Panel for Evaluation
- [x] Keyboard Capture Component to use for keyboard-shortcuts instead of buttons for controlling the evaluation
- [x] Scroll the viewport:
  - [x] on Click Run/Step
  - [x] on Click Clone Expression
  - [x] on Add Box -- Editor to the viewport
- [ ] Breakpoints
  - [x] Remove Breakpoint
  - [ ] Select which type of Breakpoint you want to attach (by tooltip menu) -- when you click on expression -> tooltip is shown
- [ ] Custom Menu switch for Untyped Lambda Box - switch off the Next-Step highlighting
- [x] Fullscreen Mode for any Box
- [ ] ~~Consider - When no Box is focused - no Box is also Active (consider pros and cons)~~
- [ ] ~~Some form of notification like in Gmail - with Undo action and information what I have just done~~
- [x] Untyped Lambda Calculus - put macros somewhere
- [ ] ~~Refactor FE - Box/Integration filtering/allowing - doesn't need to be so universal and complex~~
- [ ] UI - make it smaller on lower-dpi displays
- [ ] ~~Teacher Mode~~
  - [ ] ~~to create the test~~
  - [ ] ~~to be able to lock markdown boxes (not necessary)~~
- [ ] ~~Exam Mode~~
  - [ ] ~~Exercise Box without evaluation~~
- [x] Hide Box Menus when user clicks elsewhere
- [ ] Add Collapse/Expand option to Markdown Boxes -> show only title
- [ ] ~~Add Box Modal - smaller + dark transparent backdrop~~
- [x] Inactive Boxes -> hide Box-Top-Bar menu items - TODO: pick which ones
- [ ] Refactor:
  - [ ] Break Points
  - [ ] React Printer

**Comment by lambduli** [comment]
I have decided that what should have been done has been done on the new branch. Closing now.
